services:
  - type: web
    name: prediccion-titanic
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python backend/manage.py collectstatic --noinput
    startCommand: gunicorn backend.titanic_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true